[[permission]]
identifier = "allow-custom-commands"
description = "Allows custom commands defined in the main crate"
commands.allow = [
    "launch_mpv_player",
    "close_native_player",
    "resize_native_player",
    "native_toggle_fullscreen",
    "native_get_fullscreen",
    "native_set_fullscreen",
    "native_get_arch",
    "native_start_drag",
    "native_play_pause",
    "native_seek",
    "native_set_volume",
    "native_set_mpv_fullscreen",
    "set_quality_profile",
    "get_subtitle_tracks",
    "set_subtitle_track",
    "set_subtitle_style",
    "native_sub_add",
    "native_sub_reload",
    "native_log",
    "search_gds",
    "ping",
    "get_mpv_state"
]
